In [1]:
import pandas as pd
import numpy as np

In [2]:
height = [5.9,5.8,5.2,5.4,6.1,5.5,6,5.3]
weight = [75,86,50,55,85,62,82,52]
gender = ['Male','Male','Female','Female','Male','Female']

In [3]:
training_df = pd.DataFrame({'height':height[:-2],'weight':weight[:-2],'gender':gender})

In [4]:
training_df.head()

height  weight  gender
0     5.9      75    Male
1     5.8      86    Male
2     5.2      50  Female
3     5.4      55  Female
4     6.1      85    Male

In [5]:
test_df = pd.DataFrame({'height':height[-2:],'weight':weight[-2:]})

In [6]:
test_df.head()

height  weight
0     6.0      82
1     5.3      52

In [7]:
def normalize(df):
    df['height'] = (df['height']-df['height'].mean())/df['height'].std()
    df['weight'] = (df['weight']-df['weight'].mean())/df['weight'].std()
    return df

In [8]:
def data_encoder(df):
    df['gender'] = df['gender'].str.lower()
    df['gender'] = df['gender'].replace({'male':1,'female':-1})
    return df

In [9]:
def training(X,w,b):
    # Intalize Bias and Weight at random
    z = np.dot(X, w) + b
    a = activation_function(z)
    return a

In [10]:
def activation_function(x):
    res = []
    for item in x:
        if item>1:
            res.append(1)
        elif item==0:
            res.append(0)
        else:
            res.append(-1)
    return np.array(res)

In [11]:
def model_test(X):
    pass

In [12]:
X = training_df.drop(columns=['gender'],inplace=False,axis=1)
y = training_df[['gender']]

In [13]:
X = normalize(X)
y = data_encoder(y)

c:\users\dipesh.poudel\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\dipesh.poudel\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
# Intalize the Weight and Bias at random
np.random.seed(0)
w = np.random.randn(2)
b = np.random.randn()

In [15]:
X = X.values
y = y.values

In [16]:
X

array([[ 0.73720978,  0.40025854],
       [ 0.44232587,  1.11423324],
       [-1.32697761, -1.22241122],
       [-0.73720978, -0.89787727],
       [ 1.32697761,  1.04932645],
       [-0.44232587, -0.44352973]])

In [17]:
y=np.array(y[0])

In [18]:
y

array([1], dtype=int64)

In [25]:
lr = 0.1
epochs = 100
for epoch in range(epochs):
    a = training(X, w, b)
    error = y - a
    w += lr * np.dot(X.T, error)
    b += lr * error.sum()
    loss = np.mean(np.square(error))
    print(f"Epoch {epoch+1}/{epochs} - Loss: {loss:.4f}")

Epoch 1/100 - Loss: 0.0000
Epoch 2/100 - Loss: 0.0000
Epoch 3/100 - Loss: 0.0000
Epoch 4/100 - Loss: 0.0000
Epoch 5/100 - Loss: 0.0000
Epoch 6/100 - Loss: 0.0000
Epoch 7/100 - Loss: 0.0000
Epoch 8/100 - Loss: 0.0000
Epoch 9/100 - Loss: 0.0000
Epoch 10/100 - Loss: 0.0000
Epoch 11/100 - Loss: 0.0000
Epoch 12/100 - Loss: 0.0000
Epoch 13/100 - Loss: 0.0000
Epoch 14/100 - Loss: 0.0000
Epoch 15/100 - Loss: 0.0000
Epoch 16/100 - Loss: 0.0000
Epoch 17/100 - Loss: 0.0000
Epoch 18/100 - Loss: 0.0000
Epoch 19/100 - Loss: 0.0000
Epoch 20/100 - Loss: 0.0000
Epoch 21/100 - Loss: 0.0000
Epoch 22/100 - Loss: 0.0000
Epoch 23/100 - Loss: 0.0000
Epoch 24/100 - Loss: 0.0000
Epoch 25/100 - Loss: 0.0000
Epoch 26/100 - Loss: 0.0000
Epoch 27/100 - Loss: 0.0000
Epoch 28/100 - Loss: 0.0000
Epoch 29/100 - Loss: 0.0000
Epoch 30/100 - Loss: 0.0000
Epoch 31/100 - Loss: 0.0000
Epoch 32/100 - Loss: 0.0000
Epoch 33/100 - Loss: 0.0000
Epoch 34/100 - Loss: 0.0000
Epoch 35/100 - Loss: 0.0000
Epoch 36/100 - Loss: 0.0000
E

In [26]:
test_df = normalize(test_df)

In [27]:
prediction = training(test_df, w, b)
prediction

array([1, 1])

In [28]:
print(w)

[ 0.84991222 -0.53666413]


In [29]:
print(b)

1.9787379841057393


In [30]:
for item in prediction:
    if item==1:
        print("The Gender is Male")
    else:
        print("The Gender is Female")

The Gender is Male
The Gender is Male
